import { useEffect, useMemo, useState } from 'react';
import { ApplicationRegistry, type AppId } from './windowManager';
import { AudioService, BluetoothService, DisplayService, NetworkService, PlatformService, PowerService, SettingsService, StorageService, ThemeService, UpdateService } from './systemServices';

type Category = 'System'|'Bluetooth & devices'|'Network & Internet'|'Personalization'|'Apps'|'Accounts'|'Time & language'|'Gaming'|'Accessibility'|'Privacy & security'|'Storage'|'Windows Update'|'About';
const categories: Category[] = ['System','Bluetooth & devices','Network & Internet','Personalization','Apps','Accounts','Time & language','Gaming','Accessibility','Privacy & security','Storage','Windows Update','About'];
const settingsIndex = [{name:'Display', category:'System', keywords:'screen monitor brightness resolution scale'}, {name:'Sound',category:'System',keywords:'audio volume mute output input'}, {name:'Power',category:'System',keywords:'battery sleep timeout'}, {name:'Wi-Fi',category:'Network & Internet',keywords:'wifi network internet wireless'}, {name:'Bluetooth',category:'Bluetooth & devices',keywords:'bluetooth devices'}, {name:'Themes',category:'Personalization',keywords:'theme wallpaper accent color'}, {name:'Installed apps',category:'Apps',keywords:'application programs'}, {name:'Your info',category:'Accounts',keywords:'user profile password sign-in'}, {name:'Date & time',category:'Time & language',keywords:'clock timezone region language'}, {name:'Accessibility',category:'Accessibility',keywords:'text size contrast motion keyboard'}, {name:'Storage',category:'Storage',keywords:'disk files usage'}, {name:'Windows Update',category:'Windows Update',keywords:'version update build'}];
const Support=({reason}:{reason:string})=><span className="setting-support">Unavailable in browser mode: {reason}</span>;
function SettingCard({title,children}:{title:string;children:React.ReactNode}){return <section className="setting-card"><h3>{title}</h3>{children}</section>}
function Display(){const [data,setData]=useState<Record<string,unknown>>({});useEffect(()=>{Promise.all([DisplayService.getResolution(),DisplayService.getScale(),DisplayService.getOrientation(),DisplayService.getBrightness(),DisplayService.getRefreshRate()]).then(x=>setData({resolution:x[0],scale:x[1],orientation:x[2],brightness:x[3],refresh:x[4]}))},[]);return <><SettingCard title="Display"><p>Display: Browser Display</p><p>Resolution: {String((data.resolution as {value?:unknown})?.value || 'Detecting…')}</p><p>Scale: {String((data.scale as {value?:unknown})?.value || 'Detecting…')}</p><p>Orientation: {String((data.orientation as {value?:unknown})?.value || 'Detecting…')}</p><Support reason="Hardware brightness and refresh rate controls require a native host."/></SettingCard><SettingCard title="Brightness and night light"><button disabled>Brightness unavailable in browser mode</button><button onClick={()=>SettingsService.set('nightLight',!SettingsService.get('nightLight',false))}>Toggle browser-safe night light preference</button></SettingCard></>}
function Sound(){const [outputs,setOutputs]=useState<string[]>([]);useEffect(()=>{AudioService.getOutputDevices().then(r=>setOutputs((r.value as string[])||[]))},[]);return <SettingCard title="Sound"><p>Output devices: {outputs.length?outputs.join(', '):'No labelled device exposed'}</p><Support reason="System volume and mute require a native host."/></SettingCard>}
function Network(){const online=NetworkService.getOnlineStatus();return <><SettingCard title="Wi-Fi"><p>Status: {online.value?'Online':'Offline'}</p><p>Connection type: {String(NetworkService.getConnectionType().value)}</p><Support reason="Available networks and Wi-Fi connection control require native Windows 4 APIs."/></SettingCard><SettingCard title="Ethernet"><Support reason="IP, gateway, DNS and link state are available in native Windows 4."/></SettingCard></>}
function Power(){const [battery,setBattery]=useState<{percentage?:number;charging?:boolean}|null>(null);useEffect(()=>{PowerService.getBattery().then(r=>setBattery(r.value as typeof battery))},[]);return <SettingCard title="Power"><p>Battery: {battery?`${battery.percentage}% ${battery.charging?'(charging)':''}`:'Unavailable in this browser'}</p><Support reason="Power mode and timeout controls require native Windows 4."/></SettingCard>}
function Personalization(){const [theme,setTheme]=useState(String(SettingsService.get('theme')));const [accent,setAccent]=useState(String(SettingsService.get('accent')));const apply=(t:string,a:string)=>{setTheme(t);setAccent(a);ThemeService.apply(t,a)};return <><SettingCard title="Theme"><select value={theme} onChange={e=>apply(e.target.value,accent)}>{ThemeService.themes.map(x=><option key={x}>{x}</option>)}</select><div className="accent-row">{ThemeService.accents.map(x=><button key={x} className={`accent-${x}`} onClick={()=>apply(theme,x)}>{x}</button>)}</div></SettingCard><SettingCard title="Appearance"><label><input type="checkbox" checked={SettingsService.get('transparency',true) as boolean} onChange={e=>SettingsService.set('transparency',e.target.checked)}/> Transparency</label></SettingCard></>}
function Apps(){const apps=Object.values(ApplicationRegistry).filter(x=>x.id!=='error');return <SettingCard title="Installed apps">{apps.map(app=><div className="installed-app" key={app.id}><span>{app.icon}</span><b>{app.name}</b><button onClick={()=>document.dispatchEvent(new CustomEvent('huskagent:launch',{detail:app.id}))}>Open</button></div>)}</SettingCard>}
function General({category}:{category:Category}){if(category==='About'){const v=UpdateService.getCurrentVersion();return <SettingCard title="HUSKAGENT WINDOWS 4"><p>Huskagent Technology Company</p><p>Version {v.version} · Build {v.build}</p><p>Platform: {PlatformService.getPlatform()} · Architecture: {navigator.platform || 'Unavailable'}</p></SettingCard>}if(category==='Storage'){const [usage,setUsage]=useState<Record<string,number>|null>(null);useEffect(()=>{StorageService.getUsage().then(setUsage)},[]);return <SettingCard title="Storage usage">{usage?Object.entries(usage).map(([k,v])=><p key={k}>{k}: {v} bytes</p>):<p>Calculating from the persistent filesystem…</p>}</SettingCard>}return <SettingCard title={category}><p>Application-level {category.toLowerCase()} preferences are ready.</p><Support reason="Hardware-backed controls will be provided by the native Windows 4 adapter."/></SettingCard>}
export function SettingsApp({onClose}:{onClose?:()=>void}){const [category,setCategory]=useState<Category>('System');const [query,setQuery]=useState('');const results=useMemo(()=>settingsIndex.filter(x=>`${x.name} ${x.category} ${x.keywords}`.toLowerCase().includes(query.toLowerCase())),[query]);const content=category==='System'?<><Display/><Sound/><Power/></>:category==='Network & Internet'?<Network/>:category==='Personalization'?<Personalization/>:category==='Apps'?<Apps/>:<General category={category}/>;return <div className="settings-app"><header className="settings-top"><div><h2>Settings</h2><small>HUSKAGENT WINDOWS 4</small></div><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find a setting"/></header>{query&&<div className="settings-search-results">{results.length?results.map(r=><button key={r.name} onClick={()=>{setCategory(r.category as Category);setQuery('')}}><b>{r.name}</b><small>{r.category} · {r.keywords}</small></button>):<span>No settings found</span>}</div>}<div className="settings-layout"><nav className="settings-sidebar">{categories.map(x=><button className={x===category?'selected':''} key={x} onClick={()=>setCategory(x)}>{x}</button>)}</nav><main className="settings-content"><h1>{category}</h1>{content}</main></div></div>}
