import { useEffect, useMemo, useState, type ReactNode } from 'react';
import { ApplicationRegistry, type AppId } from './windowManager';
import { AudioService, BluetoothService, DisplayService, NetworkService, PlatformService, PowerService, SettingsService, StorageService, SystemEventBus, ThemeService, UpdateService } from './systemServices';
type Category='System'|'Bluetooth & devices'|'Network & Internet'|'Personalization'|'Apps'|'Accounts'|'Time & language'|'Gaming'|'Accessibility'|'Privacy & security'|'Storage'|'Windows Update'|'About';
const categories:Category[]=['System','Bluetooth & devices','Network & Internet','Personalization','Apps','Accounts','Time & language','Gaming','Accessibility','Privacy & security','Storage','Windows Update','About'];
const index=[{name:'Display',category:'System',keywords:'screen monitor brightness resolution scale'},{name:'Sound',category:'System',keywords:'audio volume mute output input'},{name:'Power',category:'System',keywords:'battery sleep timeout'},{name:'Wi-Fi',category:'Network & Internet',keywords:'wifi network internet wireless'},{name:'Bluetooth',category:'Bluetooth & devices',keywords:'bluetooth devices'},{name:'Themes',category:'Personalization',keywords:'theme wallpaper accent color'},{name:'Installed apps',category:'Apps',keywords:'application programs'},{name:'Your info',category:'Accounts',keywords:'user profile password sign-in'},{name:'Date & time',category:'Time & language',keywords:'clock timezone region language'},{name:'Accessibility',category:'Accessibility',keywords:'text size contrast motion keyboard'},{name:'Storage',category:'Storage',keywords:'disk files usage'},{name:'Windows Update',category:'Windows Update',keywords:'version update build'}];
const Support=({reason}:{reason:string})=><span className="setting-support">Unavailable in browser mode: {reason}</span>;const Card=({title,children}:{title:string;children:ReactNode})=><section className="setting-card"><h3>{title}</h3>{children}</section>;
function Display(){const[data,setData]=useState<Record<string,unknown>>({});useEffect(()=>{Promise.all([DisplayService.getResolution(),DisplayService.getScale(),DisplayService.getOrientation(),DisplayService.getBrightness(),DisplayService.getRefreshRate()]).then(([resolution,scale,orientation,brightness,refresh])=>setData({resolution,scale,orientation,brightness,refresh}))},[]);return <><Card title="Display"><p>Resolution: {String((data.resolution as{value?:unknown})?.value||'Detecting…')}</p><p>Scale: {String((data.scale as{value?:unknown})?.value||'Detecting…')}</p><p>Orientation: {String((data.orientation as{value?:unknown})?.value||'Detecting…')}</p><p>Brightness: {(data.brightness as{supported?:boolean})?.supported?'Available':'Unavailable'}</p><p>Refresh rate: {(data.refresh as{supported?:boolean})?.supported?String((data.refresh as{value?:unknown}).value):'Unavailable'}</p></Card><Card title="Night light"><label><input type="checkbox" checked={SettingsService.get('nightLight',false) as boolean} onChange={e=>SettingsService.set('nightLight',e.target.checked)}/> Browser-safe preference</label><Support reason="Hardware display controls require a native host."/></Card></>}
function Sound(){const[outputs,setOutputs]=useState<string[]>([]);useEffect(()=>{AudioService.getOutputDevices().then(r=>setOutputs((r.value as string[])||[]))},[]);return <Card title="Sound"><p>Output devices: {outputs.length?outputs.join(', '):'No labelled output exposed'}</p><Support reason="System volume and mute require a native host."/></Card>}
function Network(){return <><Card title="Wi-Fi"><p>Status: {NetworkService.getOnlineStatus().value?'Online':'Offline'}</p><p>Connection type: {String(NetworkService.getConnectionType().value)}</p><Support reason="Wi-Fi networks and connection control require native APIs."/></Card><Card title="Ethernet"><Support reason="IP, gateway and DNS are available in native Windows 4."/></Card></>}
function Bluetooth(){return <Card title="Bluetooth"><p>Web Bluetooth: {BluetoothService.isSupported()?'Available':'Unavailable'}</p><Support reason="Device enumeration requires explicit permission or native APIs."/></Card>}
function Power(){const[battery,setBattery]=useState<{percentage?:number;charging?:boolean}|null>(null);useEffect(()=>{PowerService.getBattery().then(r=>setBattery(r.value as typeof battery))},[]);return <Card title="Power"><p>Battery: {battery?`${battery.percentage}% ${battery.charging?'(charging)':''}`:'Unavailable in this browser'}</p><Support reason="Power modes and timeouts require native APIs."/></Card>}
function Personalization(){const[theme,setTheme]=useState(String(SettingsService.get('theme'))),[accent,setAccent]=useState(String(SettingsService.get('accent')));const apply=(t:string,a:string)=>{setTheme(t);setAccent(a);ThemeService.apply(t,a)};return <Card title="Theme"><select value={theme} onChange={e=>apply(e.target.value,accent)}>{ThemeService.themes.map(x=><option key={x}>{x}</option>)}</select><div className="accent-row">{ThemeService.accents.map(x=><button key={x} className={`accent-${x}`} onClick={()=>apply(theme,x)}>{x}</button>)}</div></Card>}
function Apps({launch}:{launch:(id:AppId)=>void}){return <Card title="Installed apps">{Object.values(ApplicationRegistry).filter(x=>x.id!=='error').map(a=><div className="installed-app" key={a.id}><span>{a.icon}</span><b>{a.name}</b><button onClick={()=>launch(a.id)}>Open</button></div>)}</Card>}
function General({category}:{category:Category}){if(category==='About'){const v=UpdateService.getCurrentVersion();return <Card title="HUSKAGENT WINDOWS 4"><p>Huskagent Technology Company</p><p>Version {v.version} · Build {v.build}</p><p>Platform: {PlatformService.getPlatform()} · Architecture: {navigator.platform||'Unavailable'}</p></Card>}return <Card title={category}><p>Application-level {category.toLowerCase()} preferences are ready.</p><Support reason="Hardware-backed controls require the native adapter."/></Card>}
export function SettingsApp({launch}:{launch:(id:AppId,args?:unknown)=>void}){const[category,setCategory]=useState<Category>('System'),[query,setQuery]=useState('');useEffect(()=>SystemEventBus.on('settingsChanged',()=>{}),[]);const results=useMemo(()=>index.filter(x=>`${x.name} ${x.category} ${x.keywords}`.toLowerCase().includes(query.toLowerCase())),[query]);const content=category==='System'?<><Display/><Sound/><Power/></>:category==='Network & Internet'?<Network/>:category==='Bluetooth & devices'?<Bluetooth/>:category==='Personalization'?<Personalization/>:category==='Apps'?<Apps launch={launch}/>:<General category={category}/>;return <div className="settings-app"><header className="settings-top"><div><h2>Settings</h2><small>HUSKAGENT WINDOWS 4</small></div><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find a setting" aria-label="Find a setting"/></header>{query&&<div className="settings-search-results">{results.length?results.map(r=><button key={r.name} onClick={()=>{setCategory(r.category as Category);setQuery('')}}><b>{r.name}</b><small>{r.category}</small></button>):<span>No settings found</span>}</div>}<div className="settings-layout"><nav className="settings-sidebar">{categories.map(x=><button className={x===category?'selected':''} key={x} onClick={()=>setCategory(x)}>{x}</button>)}</nav><main className="settings-content"><h1>{category}</h1>{content}</main></div></div>}
ApplicationRegistry.settings.component=(_args,api)=><SettingsApp launch={api.launch}/>;
