import { ApplicationRegistry, type AppId } from './windowManager';
import { fileSystem } from './filesystem';
export interface UserProfile { id:string; name:string; role:string; avatar:string }
export interface RecentItem { id:string; type:'application'|'file'|'folder'; name:string; path?:string; icon:string; lastOpened:string }
export interface SearchResult { id:string; type:'application'|'file'|'folder'|'setting'|'recent'; name:string; icon:string; description:string; score:number; action:()=>void }
const userKey='huskagent-user', recentKey='huskagent-recent', startKey='huskagent-start-pins', taskKey='huskagent-taskbar-pins';
const defaults:AppId[]=['file-explorer','browser','music','video-player','husky-studio','settings','notepad','paint','calculator','games'];
export const UserService={getCurrentUser():UserProfile{try{return JSON.parse(localStorage.getItem(userKey)||'null')||{id:'local-user',name:'Onalo Mhobo',role:'Administrator',avatar:'O'}}catch{return {id:'local-user',name:'Onalo Mhobo',role:'Administrator',avatar:'O'}}},updateUser(p:Partial<UserProfile>){const next={...this.getCurrentUser(),...p};localStorage.setItem(userKey,JSON.stringify(next));return next},getUserAvatar(){return this.getCurrentUser().avatar},getUserRole(){return this.getCurrentUser().role}};
export const RecentItemsService={list():RecentItem[]{try{return JSON.parse(localStorage.getItem(recentKey)||'[]')}catch{return []}},record(item:Omit<RecentItem,'lastOpened'>){const next=[{...item,lastOpened:new Date().toISOString()},...this.list().filter(x=>x.id!==item.id)].slice(0,25);localStorage.setItem(recentKey,JSON.stringify(next));return next}};
const readPins=(key:string,fallback:AppId[])=>{try{const value=JSON.parse(localStorage.getItem(key)||'null');return Array.isArray(value)?value as AppId[]:fallback}catch{return fallback}};
export const PinningService={getStartPins:()=>readPins(startKey,defaults),getTaskbarPins:()=>readPins(taskKey,['file-explorer','browser','music','settings']),setStartPins:(v:AppId[])=>localStorage.setItem(startKey,JSON.stringify(v)),setTaskbarPins:(v:AppId[])=>localStorage.setItem(taskKey,JSON.stringify(v)),toggleStart(id:AppId){const v=this.getStartPins();this.setStartPins(v.includes(id)?v.filter(x=>x!==id):[...v,id])},toggleTaskbar(id:AppId){const v=this.getTaskbarPins();this.setTaskbarPins(v.includes(id)?v.filter(x=>x!==id):[...v,id])}};
const score=(name:string,description:string,q:string)=>{const n=name.toLowerCase(),d=description.toLowerCase();return n===q?100:n.startsWith(q)?80:n.includes(q)?60:d.includes(q)?20:0};
export class SearchService{constructor(private launch:(id:AppId,args?:unknown)=>void){} async searchAll(query:string):Promise<SearchResult[]>{const q=query.trim().toLowerCase();if(!q)return[];const apps=Object.values(ApplicationRegistry).filter(a=>a.id!=='error').map(a=>({id:`app-${a.id}`,type:'application' as const,name:a.name,icon:a.icon,description:'Application',score:score(a.name,'application',q),action:()=>{RecentItemsService.record({id:`app-${a.id}`,type:'application',name:a.name,icon:a.icon});this.launch(a.id)}})).filter(x=>x.score>0);const nodes=await fileSystem.search(q);const files=nodes.map(n=>({id:n.id,type:(n.kind==='folder'?'folder':'file') as 'folder'|'file',name:n.name,icon:n.kind==='folder'?'📁':'📄',description:`${n.kind==='folder'?'Folder':n.extension||'File'} · ${n.parent}`,score:score(n.name,n.path,q),action:()=>{RecentItemsService.record({id:n.id,type:n.kind==='folder'?'folder':'file',name:n.name,path:n.path,icon:n.kind==='folder'?'📁':'📄'});this.launch('file-explorer',{path:n.kind==='folder'?n.path:n.parent})}})).filter(x=>x.score>0);const settings=[['Wi-Fi','📶','Network & Internet'],['Brightness','☀️','System'],['Sound','🔊','System'],['Password','🔐','Accounts']].map(([name,icon,description])=>({id:`setting-${name}`,type:'setting' as const,name,icon,description,score:score(name,description,q),action:()=>this.launch('settings',{category:description})})).filter(x=>x.score>0);return[...apps,...files,...settings].sort((a,b)=>b.score-a.score).slice(0,30)}}
