import React, { createContext, useCallback, useContext, useEffect, useMemo, useRef, useState } from 'react';
import type { ReactNode, PointerEvent as ReactPointerEvent } from 'react';
import { fileSystem } from './filesystem';
import { FileExplorer } from './FileExplorer';

export type AppId = 'file-explorer' | 'this-pc' | 'browser' | 'music' | 'video-player' | 'husky-studio' | 'settings' | 'notepad' | 'paint' | 'calculator' | 'games' | 'error';
export type SnapSide = 'left' | 'right' | null;
export interface WindowRecord { id:string; appId:AppId; title:string; icon:string; x:number; y:number; width:number; height:number; minWidth:number; minHeight:number; zIndex:number; isOpen:boolean; isMinimized:boolean; isMaximized:boolean; isFocused:boolean; isResizable:boolean; isDraggable:boolean; canClose:boolean; canMinimize:boolean; canMaximize:boolean; restore?:{x:number;y:number;width:number;height:number}; snap:SnapSide; args?:unknown; }
export interface AppDefinition { id:AppId; name:string; icon:string; defaultWidth:number; defaultHeight:number; minWidth:number; minHeight:number; canResize?:boolean; canMaximize?:boolean; canMinimize?:boolean; component:(args:unknown, api:{launch:(id:AppId,args?:unknown)=>void; showProperties:(value:unknown)=>void})=>ReactNode; }

const icons:Record<AppId,string>={ 'file-explorer':'📁','this-pc':'💻',browser:'🌐',music:'🎵','video-player':'🎬','husky-studio':'🎚️',settings:'⚙️',notepad:'📝',paint:'🎨',calculator:'🧮',games:'🎮',error:'⚠️' };
const names:Record<AppId,string>={ 'file-explorer':'My Files','this-pc':'This PC',browser:'Browser',music:'Music Player','video-player':'Video Player','husky-studio':'Husky Studio',settings:'Settings',notepad:'Notepad',paint:'Paint',calculator:'Calculator',games:'Games',error:'Application Error' };

const Placeholder=({id}:{id:AppId})=><div className="wm-placeholder"><div className="wm-placeholder-icon">{icons[id]}</div><h2>{names[id]}</h2><p>This application launch point is registered with the Windows 4 Window Manager. Its subsystem can be implemented without changing window behavior.</p></div>;
const registry:Record<AppId,AppDefinition> = {} as Record<AppId,AppDefinition>;
for(const id of Object.keys(names) as AppId[]) registry[id]={id,name:names[id],icon:icons[id],defaultWidth:id==='file-explorer'||id==='this-pc'?900:560,defaultHeight:id==='file-explorer'||id==='this-pc'?580:380,minWidth:id==='file-explorer'||id==='this-pc'?520:300,minHeight:id==='file-explorer'||id==='this-pc'?350:220,canResize:true,canMaximize:true,canMinimize:true,component:(args,api)=>id==='file-explorer'||id==='this-pc'?<FileExplorer initialPath={id==='this-pc'?'This PC':((args as {path?:string}|undefined)?.path??'C:')} onLaunch={(node)=>api.launch(association(node.extension))} onProperties={api.showProperties}/>:<Placeholder id={id}/>};
function association(ext?:string):AppId { const e=ext?.toUpperCase(); if(e==='TXT'||e==='DOC'||e==='DOCX')return 'notepad'; if(e==='MP3'||e==='WAV')return 'music'; if(e==='MP4')return 'video-player'; if(e==='PNG'||e==='JPG'||e==='JPEG'||e==='GIF')return 'paint'; return e==='PDF'?'browser':'file-explorer'; }

interface ManagerApi { windows:WindowRecord[]; activeId:string|null; workspace:{width:number;height:number}; openWindow:(appId:AppId,args?:unknown)=>string; closeWindow:(id:string)=>void; minimizeWindow:(id:string)=>void; maximizeWindow:(id:string)=>void; restoreWindow:(id:string)=>void; focusWindow:(id:string)=>void; moveWindow:(id:string,x:number,y:number)=>void; resizeWindow:(id:string,rect:Partial<Pick<WindowRecord,'x'|'y'|'width'|'height'>>)=>void; toggleMaximize:(id:string)=>void; getWindow:(id:string)=>WindowRecord|undefined; launchApp:(id:AppId,args?:unknown)=>string; }
const ManagerContext=createContext<ManagerApi|null>(null);
export const useWindowManager=()=>{const value=useContext(ManagerContext);if(!value)throw new Error('WindowManagerProvider is required');return value;};
const BASE_Z=100, MIN_VISIBLE=40, TASKBAR=64;
export function WindowManagerProvider({children}:{children:ReactNode}){const [windows,setWindows]=useState<WindowRecord[]>([]);const [activeId,setActiveId]=useState<string|null>(null);const [workspace,setWorkspace]=useState({width:innerWidth,height:innerHeight-TASKBAR});const z=useRef(BASE_Z);
 useEffect(()=>{const onResize=()=>setWorkspace({width:innerWidth,height:innerHeight-TASKBAR});addEventListener('resize',onResize);return()=>removeEventListener('resize',onResize)},[]);
 const focusWindow=useCallback((id:string)=>{z.current+=1;setActiveId(id);setWindows(ws=>ws.map(w=>({...w,isFocused:w.id===id,zIndex:w.id===id?z.current:w.zIndex})))},[]);
 const openWindow=useCallback((appId:AppId,args?:unknown)=>{const app=registry[appId]??registry.error;const id=`${appId}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;z.current+=1;const offset=windows.length*22;const width=Math.min(app.defaultWidth,Math.max(app.minWidth,workspace.width-24));const height=Math.min(app.defaultHeight,Math.max(app.minHeight,workspace.height-24));const w:WindowRecord={id,appId,title:app.name,icon:app.icon,x:Math.max(8,(workspace.width-width)/2+offset%160),y:Math.max(8,(workspace.height-height)/2+offset%100),width,height,minWidth:app.minWidth,minHeight:app.minHeight,zIndex:z.current,isOpen:true,isMinimized:false,isMaximized:false,isFocused:true,isResizable:app.canResize!==false,isDraggable:true,canClose:true,canMinimize:app.canMinimize!==false,canMaximize:app.canMaximize!==false,snap:null,args};setWindows(ws=>[...ws.map(x=>({...x,isFocused:false})),w]);setActiveId(id);return id},[workspace,windows.length]);
 const update=useCallback((id:string,patch:Partial<WindowRecord>)=>setWindows(ws=>ws.map(w=>w.id===id?{...w,...patch}:w)),[]);
 const closeWindow=useCallback((id:string)=>{setWindows(ws=>ws.filter(w=>w.id!==id));setActiveId(id===activeId?null:activeId)},[activeId]);
 const minimizeWindow=useCallback((id:string)=>{update(id,{isMinimized:true,isFocused:false});setActiveId(x=>x===id?null:x)},[update]);
 const restoreWindow=useCallback((id:string)=>{update(id,{isMinimized:false});focusWindow(id)},[update,focusWindow]);
 const maximizeWindow=useCallback((id:string)=>setWindows(ws=>ws.map(w=>{if(w.id!==id)return w;const restore={x:w.x,y:w.y,width:w.width,height:w.height};return {...w,restore,isMaximized:true,isMinimized:false,x:4,y:4,width:Math.max(w.minWidth,workspace.width-8),height:Math.max(w.minHeight,workspace.height-8),snap:null}})),[workspace]);
 const restoreBounds=useCallback((id:string)=>setWindows(ws=>ws.map(w=>{if(w.id!==id)return w;const r=w.restore??{x:100,y:80,width:w.width,height:w.height};return {...w,...r,isMaximized:false,snap:null}})),[]);
 const toggleMaximize=useCallback((id:string)=>{const w=windows.find(x=>x.id===id);if(w?.isMaximized)restoreBounds(id);else maximizeWindow(id);focusWindow(id)},[windows,restoreBounds,maximizeWindow,focusWindow]);
 const moveWindow=useCallback((id:string,x:number,y:number)=>setWindows(ws=>ws.map(w=>w.id!==id?w:{...w,x:Math.max(MIN_VISIBLE-workspace.width+w.width,Math.min(workspace.width-MIN_VISIBLE,x)),y:Math.max(0,Math.min(workspace.height-MIN_VISIBLE,y)),isMaximized:false})),[workspace]);
 const resizeWindow=useCallback((id:string,rect:Partial<Pick<WindowRecord,'x'|'y'|'width'|'height'>>)=>setWindows(ws=>ws.map(w=>{if(w.id!==id)return w;let x=rect.x??w.x,y=rect.y??w.y,width=Math.max(w.minWidth,rect.width??w.width),height=Math.max(w.minHeight,rect.height??w.height);x=Math.max(0,Math.min(workspace.width-MIN_VISIBLE,x));y=Math.max(0,Math.min(workspace.height-MIN_VISIBLE,y));return {...w,x,y,width,height,isMaximized:false}})),[workspace]);
 const value=useMemo(()=>({windows,activeId,workspace,openWindow,closeWindow,minimizeWindow,maximizeWindow,restoreWindow,focusWindow,moveWindow,resizeWindow,toggleMaximize,getWindow:(id:string)=>windows.find(w=>w.id===id),launchApp:openWindow}),[windows,activeId,workspace,openWindow,closeWindow,minimizeWindow,maximizeWindow,restoreWindow,focusWindow,moveWindow,resizeWindow,toggleMaximize]);return <ManagerContext.Provider value={value}>{children}</ManagerContext.Provider>;
}

function WindowControls({window}:{window:WindowRecord}){const wm=useWindowManager();return <div className="wm-controls"><button aria-label={`Minimize ${window.title}`} disabled={!window.canMinimize} onClick={()=>wm.minimizeWindow(window.id)}>−</button><button aria-label={`${window.isMaximized?'Restore':'Maximize'} ${window.title}`} disabled={!window.canMaximize} onClick={()=>wm.toggleMaximize(window.id)}>□</button><button aria-label={`Close ${window.title}`} disabled={!window.canClose} onClick={()=>wm.closeWindow(window.id)}>×</button></div>}
function WindowView({window,showProperties}:{window:WindowRecord;showProperties:(value:unknown)=>void}){const wm=useWindowManager();const drag=useRef<{mode:'move'|'resize';edge:string;ox:number;oy:number;start:WindowRecord}|null>(null);const [preview,setPreview]=useState<SnapSide|null>(null);const app=registry[window.appId]??registry.error;
 const pointerMove=(e:ReactPointerEvent)=>{const d=drag.current;if(!d)return;e.currentTarget.setPointerCapture?.(e.pointerId);if(d.mode==='move'){const x=e.clientX-d.ox,y=e.clientY-d.oy;setPreview(e.clientX<16?'left':e.clientX>wm.workspace.width-16?'right':e.clientY<12?'left':null);wm.moveWindow(window.id,x,y)}else{const s=d.start;let x=s.x,y=s.y,w=s.width,h=s.height;if(d.edge.includes('e'))w=e.clientX-s.x;if(d.edge.includes('s'))h=e.clientY-s.y;if(d.edge.includes('w')){x=e.clientX;w=s.x+s.width-x}if(d.edge.includes('n')){y=e.clientY;h=s.y+s.height-y}wm.resizeWindow(window.id,{x,y,width:w,height:h})}};
 const end=()=>{if(preview==='left'||preview==='right'){const half=wm.workspace.width/2;wm.resizeWindow(window.id,{x:preview==='left'?4:half,y:4,width:half-6,height:wm.workspace.height-8});}setPreview(null);drag.current=null};
 const startMove=(e:ReactPointerEvent)=>{if(e.button!==0||!window.isDraggable)return;wm.focusWindow(window.id);const r=e.currentTarget.parentElement!.getBoundingClientRect();drag.current={mode:'move',edge:'',ox:e.clientX-r.left,oy:e.clientY-r.top,start:window};};
 const startResize=(edge:string,e:ReactPointerEvent)=>{e.stopPropagation();wm.focusWindow(window.id);drag.current={mode:'resize',edge,ox:e.clientX,oy:e.clientY,start:window};};
 const body=(()=>{try{return app.component(window.args,{launch:wm.launchApp,showProperties})}catch{return <ErrorWindow onRetry={()=>wm.restoreWindow(window.id)} onClose={()=>wm.closeWindow(window.id)}/>}})();
 if(window.isMinimized)return null; return <><article className={`wm-window ${window.isFocused?'focused':''}`} style={{left:window.x,top:window.y,width:window.width,height:window.height,zIndex:window.zIndex}} onPointerDown={()=>wm.focusWindow(window.id)} onPointerMove={pointerMove} onPointerUp={end}><header className="wm-header" onPointerDown={startMove} onDoubleClick={()=>wm.toggleMaximize(window.id)} onContextMenu={e=>{e.preventDefault();}}><span className="wm-title"><span>{window.icon}</span>{window.title}</span><WindowControls window={window}/></header><div className="wm-content">{body}</div>{window.isResizable&&['n','s','e','w','ne','nw','se','sw'].map(edge=><span key={edge} className={`wm-resize wm-${edge}`} onPointerDown={e=>startResize(edge,e)}/>)}</article>{preview&&<div className={`wm-snap-preview ${preview}`}/></>}
}
function ErrorWindow({onRetry,onClose}:{onRetry:()=>void;onClose:()=>void}){return <div className="wm-error"><h2>Application failed to start.</h2><p>The application reported an error but the desktop is still running.</p><button onClick={onRetry}>Retry</button><button onClick={onClose}>Close</button></div>}

export function WindowManager({showProperties}:{showProperties:(value:unknown)=>void}){const wm=useWindowManager();return <>{wm.windows.map(w=><WindowView key={w.id} window={w} showProperties={showProperties}/>)}</>}
export const ApplicationRegistry=registry;
